package com.londroid.askmyfriends.persistence.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.londroid.askmyfriends.persistence.greendao.domain.Owner;
import com.londroid.askmyfriends.persistence.greendao.domain.Question;

import com.londroid.askmyfriends.persistence.greendao.domain.Survey;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SURVEY.
*/
public class SurveyDao extends AbstractDao<Survey, Long> {

    public static final String TABLENAME = "SURVEY";

    /**
     * Properties of entity Survey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property CreationDate = new Property(2, java.util.Date.class, "creationDate", false, "CREATION_DATE");
        public final static Property ModificationDate = new Property(3, java.util.Date.class, "modificationDate", false, "MODIFICATION_DATE");
        public final static Property ChoiceType = new Property(4, String.class, "choiceType", false, "CHOICE_TYPE");
        public final static Property QuestionId = new Property(5, long.class, "questionId", false, "QUESTION_ID");
        public final static Property OwnerId = new Property(6, long.class, "ownerId", false, "OWNER_ID");
    };

    private DaoSession daoSession;

    private Query<Survey> owner_SurveyListQuery;

    public SurveyDao(DaoConfig config) {
        super(config);
    }
    
    public SurveyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SURVEY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TITLE' TEXT NOT NULL ," + // 1: title
                "'CREATION_DATE' INTEGER," + // 2: creationDate
                "'MODIFICATION_DATE' INTEGER," + // 3: modificationDate
                "'CHOICE_TYPE' TEXT," + // 4: choiceType
                "'QUESTION_ID' INTEGER NOT NULL ," + // 5: questionId
                "'OWNER_ID' INTEGER NOT NULL );"); // 6: ownerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SURVEY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Survey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        java.util.Date creationDate = entity.getCreationDate();
        if (creationDate != null) {
            stmt.bindLong(3, creationDate.getTime());
        }
 
        java.util.Date modificationDate = entity.getModificationDate();
        if (modificationDate != null) {
            stmt.bindLong(4, modificationDate.getTime());
        }
 
        String choiceType = entity.getChoiceType();
        if (choiceType != null) {
            stmt.bindString(5, choiceType);
        }
        stmt.bindLong(6, entity.getQuestionId());
        stmt.bindLong(7, entity.getOwnerId());
    }

    @Override
    protected void attachEntity(Survey entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Survey readEntity(Cursor cursor, int offset) {
        Survey entity = new Survey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // creationDate
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // modificationDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // choiceType
            cursor.getLong(offset + 5), // questionId
            cursor.getLong(offset + 6) // ownerId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Survey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setCreationDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setModificationDate(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setChoiceType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQuestionId(cursor.getLong(offset + 5));
        entity.setOwnerId(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Survey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Survey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "surveyList" to-many relationship of Owner. */
    public List<Survey> _queryOwner_SurveyList(long ownerId) {
        synchronized (this) {
            if (owner_SurveyListQuery == null) {
                QueryBuilder<Survey> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.OwnerId.eq(null));
                owner_SurveyListQuery = queryBuilder.build();
            }
        }
        Query<Survey> query = owner_SurveyListQuery.forCurrentThread();
        query.setParameter(0, ownerId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getQuestionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getOwnerDao().getAllColumns());
            builder.append(" FROM SURVEY T");
            builder.append(" LEFT JOIN QUESTION T0 ON T.'QUESTION_ID'=T0.'_id'");
            builder.append(" LEFT JOIN OWNER T1 ON T.'OWNER_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Survey loadCurrentDeep(Cursor cursor, boolean lock) {
        Survey entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Question question = loadCurrentOther(daoSession.getQuestionDao(), cursor, offset);
         if(question != null) {
            entity.setQuestion(question);
        }
        offset += daoSession.getQuestionDao().getAllColumns().length;

        Owner owner = loadCurrentOther(daoSession.getOwnerDao(), cursor, offset);
         if(owner != null) {
            entity.setOwner(owner);
        }

        return entity;    
    }

    public Survey loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Survey> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Survey> list = new ArrayList<Survey>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Survey> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Survey> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
