package com.londroid.askmyfriends.persistence.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.londroid.askmyfriends.persistence.greendao.domain.Question;
import com.londroid.askmyfriends.persistence.greendao.domain.Survey;
import com.londroid.askmyfriends.persistence.greendao.domain.Answer;
import com.londroid.askmyfriends.persistence.greendao.domain.Vote;
import com.londroid.askmyfriends.persistence.greendao.domain.Owner;
import com.londroid.askmyfriends.persistence.greendao.domain.Juror;
import com.londroid.askmyfriends.persistence.greendao.domain.Comment;
import com.londroid.askmyfriends.persistence.greendao.domain.JurorSurvey;

import com.londroid.askmyfriends.persistence.greendao.dao.QuestionDao;
import com.londroid.askmyfriends.persistence.greendao.dao.SurveyDao;
import com.londroid.askmyfriends.persistence.greendao.dao.AnswerDao;
import com.londroid.askmyfriends.persistence.greendao.dao.VoteDao;
import com.londroid.askmyfriends.persistence.greendao.dao.OwnerDao;
import com.londroid.askmyfriends.persistence.greendao.dao.JurorDao;
import com.londroid.askmyfriends.persistence.greendao.dao.CommentDao;
import com.londroid.askmyfriends.persistence.greendao.dao.JurorSurveyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionDaoConfig;
    private final DaoConfig surveyDaoConfig;
    private final DaoConfig answerDaoConfig;
    private final DaoConfig voteDaoConfig;
    private final DaoConfig ownerDaoConfig;
    private final DaoConfig jurorDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig jurorSurveyDaoConfig;

    private final QuestionDao questionDao;
    private final SurveyDao surveyDao;
    private final AnswerDao answerDao;
    private final VoteDao voteDao;
    private final OwnerDao ownerDao;
    private final JurorDao jurorDao;
    private final CommentDao commentDao;
    private final JurorSurveyDao jurorSurveyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        surveyDaoConfig = daoConfigMap.get(SurveyDao.class).clone();
        surveyDaoConfig.initIdentityScope(type);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        voteDaoConfig = daoConfigMap.get(VoteDao.class).clone();
        voteDaoConfig.initIdentityScope(type);

        ownerDaoConfig = daoConfigMap.get(OwnerDao.class).clone();
        ownerDaoConfig.initIdentityScope(type);

        jurorDaoConfig = daoConfigMap.get(JurorDao.class).clone();
        jurorDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        jurorSurveyDaoConfig = daoConfigMap.get(JurorSurveyDao.class).clone();
        jurorSurveyDaoConfig.initIdentityScope(type);

        questionDao = new QuestionDao(questionDaoConfig, this);
        surveyDao = new SurveyDao(surveyDaoConfig, this);
        answerDao = new AnswerDao(answerDaoConfig, this);
        voteDao = new VoteDao(voteDaoConfig, this);
        ownerDao = new OwnerDao(ownerDaoConfig, this);
        jurorDao = new JurorDao(jurorDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        jurorSurveyDao = new JurorSurveyDao(jurorSurveyDaoConfig, this);

        registerDao(Question.class, questionDao);
        registerDao(Survey.class, surveyDao);
        registerDao(Answer.class, answerDao);
        registerDao(Vote.class, voteDao);
        registerDao(Owner.class, ownerDao);
        registerDao(Juror.class, jurorDao);
        registerDao(Comment.class, commentDao);
        registerDao(JurorSurvey.class, jurorSurveyDao);
    }
    
    public void clear() {
        questionDaoConfig.getIdentityScope().clear();
        surveyDaoConfig.getIdentityScope().clear();
        answerDaoConfig.getIdentityScope().clear();
        voteDaoConfig.getIdentityScope().clear();
        ownerDaoConfig.getIdentityScope().clear();
        jurorDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        jurorSurveyDaoConfig.getIdentityScope().clear();
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public SurveyDao getSurveyDao() {
        return surveyDao;
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public VoteDao getVoteDao() {
        return voteDao;
    }

    public OwnerDao getOwnerDao() {
        return ownerDao;
    }

    public JurorDao getJurorDao() {
        return jurorDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public JurorSurveyDao getJurorSurveyDao() {
        return jurorSurveyDao;
    }

}
