package com.londroid.askmyfriends.persistence.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.londroid.askmyfriends.persistence.greendao.domain.Answer;
import com.londroid.askmyfriends.persistence.greendao.domain.Comment;
import com.londroid.askmyfriends.persistence.greendao.domain.Juror;

import com.londroid.askmyfriends.persistence.greendao.domain.Vote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VOTE.
*/
public class VoteDao extends AbstractDao<Vote, Long> {

    public static final String TABLENAME = "VOTE";

    /**
     * Properties of entity Vote.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AnswerId = new Property(1, long.class, "answerId", false, "ANSWER_ID");
        public final static Property JurorId = new Property(2, long.class, "jurorId", false, "JUROR_ID");
        public final static Property CommentId = new Property(3, long.class, "commentId", false, "COMMENT_ID");
    };

    private DaoSession daoSession;


    public VoteDao(DaoConfig config) {
        super(config);
    }
    
    public VoteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VOTE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ANSWER_ID' INTEGER NOT NULL ," + // 1: answerId
                "'JUROR_ID' INTEGER NOT NULL ," + // 2: jurorId
                "'COMMENT_ID' INTEGER NOT NULL );"); // 3: commentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VOTE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Vote entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getAnswerId());
        stmt.bindLong(3, entity.getJurorId());
        stmt.bindLong(4, entity.getCommentId());
    }

    @Override
    protected void attachEntity(Vote entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Vote readEntity(Cursor cursor, int offset) {
        Vote entity = new Vote( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // answerId
            cursor.getLong(offset + 2), // jurorId
            cursor.getLong(offset + 3) // commentId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Vote entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAnswerId(cursor.getLong(offset + 1));
        entity.setJurorId(cursor.getLong(offset + 2));
        entity.setCommentId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Vote entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Vote entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAnswerDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getJurorDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getCommentDao().getAllColumns());
            builder.append(" FROM VOTE T");
            builder.append(" LEFT JOIN ANSWER T0 ON T.'ANSWER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN JUROR T1 ON T.'JUROR_ID'=T1.'_id'");
            builder.append(" LEFT JOIN COMMENT T2 ON T.'COMMENT_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Vote loadCurrentDeep(Cursor cursor, boolean lock) {
        Vote entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Answer answer = loadCurrentOther(daoSession.getAnswerDao(), cursor, offset);
         if(answer != null) {
            entity.setAnswer(answer);
        }
        offset += daoSession.getAnswerDao().getAllColumns().length;

        Juror juror = loadCurrentOther(daoSession.getJurorDao(), cursor, offset);
         if(juror != null) {
            entity.setJuror(juror);
        }
        offset += daoSession.getJurorDao().getAllColumns().length;

        Comment comment = loadCurrentOther(daoSession.getCommentDao(), cursor, offset);
         if(comment != null) {
            entity.setComment(comment);
        }

        return entity;    
    }

    public Vote loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Vote> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Vote> list = new ArrayList<Vote>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Vote> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Vote> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
